# Generated by Django 3.2.6 on 2021-09-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socioapp', '0004_likepost'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowersCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=500)),
                ('user', models.CharField(max_length=500)),
            ],
        ),
    ]
